use clap::{Arg, Command};

pub fn build_cli() -> Command {
    Command::new("mycochip")
        .about("Create a network of devices")
        .subcommand(Command::new("up")
            .about("Bring up a network of devices in a given configuration")
            .arg(Arg::new("config-file")
                .help("Configuration file")
                .required(false)))
        .subcommand(Command::new("list")
            .about("List running machines"))
        .subcommand(Command::new("pin")
            .about("Set or get a pin state")
            .arg(Arg::new("node")
                .help("Node name")
                .required(true))
            .arg(Arg::new("port")
                .help("Port name")
                .required(true))
            .arg(Arg::new("pin")
                .value_parser(clap::value_parser!(u8))
                .help("Pin number")
                .required(true))
            .arg(Arg::new("state")
                .value_parser(clap::value_parser!(bool))
                .help("Pin state")
                .required(false)))
        .subcommand(Command::new("rx")
            .about("Read characters sent by a node")
            .arg(Arg::new("node")
                .help("Node name")
                .required(true)))
}
